/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe;
import javax.swing.JOptionPane;

/**
 *
 * @author L
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chklt = new javax.swing.JCheckBox();
        chkcc = new javax.swing.JCheckBox();
        chkpft = new javax.swing.JCheckBox();
        chkbc = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        txtbc = new javax.swing.JTextField();
        txtlt = new javax.swing.JTextField();
        txtcc = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        txtpft = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        chklt.setText("Lemon Tea");
        chklt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkltActionPerformed(evt);
            }
        });
        jPanel1.add(chklt);
        chklt.setBounds(80, 90, 82, 23);

        chkcc.setText("Chocolate Cake");
        chkcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkccActionPerformed(evt);
            }
        });
        jPanel1.add(chkcc);
        chkcc.setBounds(320, 90, 110, 23);

        chkpft.setText("Perfait");
        chkpft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkpftActionPerformed(evt);
            }
        });
        jPanel1.add(chkpft);
        chkpft.setBounds(80, 240, 60, 23);

        chkbc.setText("Black Coffe");
        chkbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbcActionPerformed(evt);
            }
        });
        jPanel1.add(chkbc);
        chkbc.setBounds(330, 230, 120, 23);

        jButton1.setText("Pesan Sekarang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(500, 330, 150, 25);

        txtbc.setEditable(false);
        txtbc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtbc.setText("0");
        jPanel1.add(txtbc);
        txtbc.setBounds(470, 230, 30, 30);

        txtlt.setEditable(false);
        txtlt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtlt.setText("0");
        jPanel1.add(txtlt);
        txtlt.setBounds(220, 90, 30, 30);

        txtcc.setEditable(false);
        txtcc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtcc.setText("0");
        jPanel1.add(txtcc);
        txtcc.setBounds(470, 90, 30, 30);
        jPanel1.add(total);
        total.setBounds(720, 50, 170, 30);

        txtpft.setEditable(false);
        txtpft.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpft.setText("0");
        jPanel1.add(txtpft);
        txtpft.setBounds(220, 240, 30, 30);

        jLabel2.setText("Rp.15.000");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 190, 130, 15);

        jLabel3.setText("Rp.20.000");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 345, 140, 15);

        jLabel4.setText("Rp.15.000");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 200, 140, 15);

        jLabel5.setText("Rp.10.000");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 340, 140, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bckgrnd/Menu.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 910, 404);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkltActionPerformed
        // TODO add your handling code here:
    if (chklt.isSelected()) {
    txtlt.setEditable(true);
    txtlt.setText("1");
    } else {
    txtlt.setEditable(false);
    txtlt.setText("0");
    }
    }//GEN-LAST:event_chkltActionPerformed

    private void chkccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkccActionPerformed
        // TODO add your handling code here:
    if (chkcc.isSelected()) {
    txtcc.setEditable(true);
    txtcc.setText("1");
    } else {
    txtcc.setEditable(false);
    txtcc.setText("0");
    }
    }//GEN-LAST:event_chkccActionPerformed

    private void chkpftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkpftActionPerformed
        // TODO add your handling code here:
    if (chkpft.isSelected()) {
    txtpft.setEditable(true);
    txtpft.setText("1");
    } else {
    txtpft.setEditable(false);
    txtpft.setText("0");
    }
    }//GEN-LAST:event_chkpftActionPerformed

    private void chkbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbcActionPerformed
        // TODO add your handling code here:
    if (chkbc.isSelected()) {
    txtbc.setEditable(true);
    txtbc.setText("1");
    } else {
    txtbc.setEditable(false);
    txtbc.setText("0");
    }
    }//GEN-LAST:event_chkbcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
boolean lDataOke = true;
// cek Ada atau tidak :
// menu dipesan tetapi tidak menuliskan Quantity
// jika ada, maka variabel lDataOke menjadi false
if (chkcc.isSelected() && txtcc.getText() == " ")
lDataOke = false;
if (chkbc.isSelected() && txtbc.getText() == " ")
lDataOke = false;
if (chkpft.isSelected() && txtpft.getText() == " ")
lDataOke = false;
if (chklt.isSelected() && txtlt.getText() == " ")
lDataOke = false;
// jika variabel lDataOke == false, berarti masih ada kesalahan
// sehingga perlu dimunculkan pesan kesalahan
if (!lDataOke) {
JOptionPane.showMessageDialog(this,
"Data Dilengkapi dahulu");
} else {
// untuk memudahkan, buat variabel baru untuk menampung data
int ncc = Integer.parseInt(txtcc.getText());
int nbc = Integer.parseInt(txtbc.getText());
int nlt = Integer.parseInt(txtlt.getText());
int npft = Integer.parseInt(txtpft.getText());
// hitung total
int nTotal = (15000 * ncc)+
(10000 * nbc)+(20000 * npft)+(15000 * nlt);
total.setText("Total Belanja anda Rp. "+nTotal);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkbc;
    private javax.swing.JCheckBox chkcc;
    private javax.swing.JCheckBox chklt;
    private javax.swing.JCheckBox chkpft;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtbc;
    private javax.swing.JTextField txtcc;
    private javax.swing.JTextField txtlt;
    private javax.swing.JTextField txtpft;
    // End of variables declaration//GEN-END:variables
}
