/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmodul6;
import java.awt.Image;
import javax.swing.*;
import java.io.*;
import javax.swing.filechooser.FileFilter;
/**
 * Nama: Leo Wahata.
 * Kelas: XII RPL.
 * NO Absen: 21.
 * @author L
 */
public class fGambar extends javax.swing.JFrame {
DefaultListModel gambar;
// buat konstanta untuk filter file
final String[] EXT= {".jpg", ".jpeg",".gif",".tiff",".png"};
/** Creates new form fGambar */
public fGambar() {
initComponents();
gambar = new DefaultListModel();
lstDaftar.setModel(gambar);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPilih = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        chkFit = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDaftar = new javax.swing.JList<>();
        jScrollPane = new javax.swing.JScrollPane();
        lblGambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPilih.setText("Pilih Gambar");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Pilihan");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        chkFit.setText("Fit Frame Gambar");

        lstDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDaftarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDaftar);

        jScrollPane.setViewportView(lblGambar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPilih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFit)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilih)
                    .addComponent(btnHapus)
                    .addComponent(chkFit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jScrollPane))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        //Atur Filter Menggunakan Class jenisFile
        //aturan mengikuti konstanta EXT
        fc.addChoosableFileFilter(new jenisFile(EXT));
        int hasil = fc.showOpenDialog(this);
        if (hasil == JFileChooser.APPROVE_OPTION) {
        //Pilih Yes
        File file = fc.getSelectedFile();
        // Ambil nama file beserta pathnya
        String nf = file.getAbsolutePath();
        // masukkan ke listData Model gambar
        gambar.addElement(nf);
        }
    }//GEN-LAST:event_btnPilihActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int index = lstDaftar.getSelectedIndex();
        //yang di-remove adalah listData model-nya
        gambar.remove(index);
        lblGambar.setIcon(null);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void lstDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDaftarMouseClicked
        // TODO add your handling code here:
        //Ambil nama file gambarnya
        String nf = lstDaftar.getSelectedValue().toString();
        // Jadikan Icon
        ImageIcon gbr = new ImageIcon(nf);
        // Jika CheckBox Fit ke Frame gambar di Check
        if (chkFit.isSelected())
        // buat gambar mempunyai lebar 200,
        // dengan tinggi menyesuaikan
        // menggunakan algoritma default
        gbr = new ImageIcon(gbr.getImage().getScaledInstance(200,
        -1, Image.SCALE_DEFAULT));
        //tampilkan gambar
        lblGambar.setIcon(gbr);
    }//GEN-LAST:event_lstDaftarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPilih;
    private javax.swing.JCheckBox chkFit;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JList<String> lstDaftar;
    // End of variables declaration//GEN-END:variables
}
