/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pmodul2;

import javax.swing.JOptionPane;

/**
 * Nama: Leo Wahata.
 * Kelas: XII RPL.
 * NO Absen: 21.
 * @author L
 */
public class fwarung extends javax.swing.JFrame {

    /** Creates new form fwarung */
    public fwarung() {
        initComponents();
        rdgCaraBayar.add(rdoCash);
        rdgCaraBayar.add(rdoBCA);
        rdgCaraBayar.add(rdoMandiri);
    
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgCaraBayar = new javax.swing.ButtonGroup();
        menu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkSoto = new javax.swing.JCheckBox();
        chkEsJeruk = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        chkEsTeh = new javax.swing.JCheckBox();
        txtSoto = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtEsTeh = new javax.swing.JTextField();
        txtEsJeruk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnKosong = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        rdoCash = new javax.swing.JRadioButton();
        rdoBCA = new javax.swing.JRadioButton();
        rdoMandiri = new javax.swing.JRadioButton();
        lblCaraBayar = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setText("Menu");

        jLabel2.setText("Quantity");

        chkSoto.setMnemonic('s');
        chkSoto.setText("Soto : Rp. 5000");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        chkEsJeruk.setMnemonic('E');
        chkEsJeruk.setText("Es Jeruk : Rp. 2000");
        chkEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsJerukActionPerformed(evt);
            }
        });

        chkSate.setMnemonic('a');
        chkSate.setText("Sate : Rp. 10000");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        chkEsTeh.setMnemonic('T');
        chkEsTeh.setText("Es Teh : Rp. 1500");
        chkEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsTehActionPerformed(evt);
            }
        });

        txtSoto.setEditable(false);
        txtSoto.setText("0");
        txtSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSotoActionPerformed(evt);
            }
        });

        txtSate.setEditable(false);
        txtSate.setText("0");
        txtSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSateActionPerformed(evt);
            }
        });

        txtEsTeh.setEditable(false);
        txtEsTeh.setText("0");
        txtEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEsTehActionPerformed(evt);
            }
        });

        txtEsJeruk.setEditable(false);
        txtEsJeruk.setText("0");
        txtEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEsJerukActionPerformed(evt);
            }
        });

        jLabel3.setText("Cara Bayar");

        lblTotal.setText("Rp. 0");

        btnKosong.setMnemonic('K');
        btnKosong.setText("Kosongkan");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        rdgCaraBayar.add(rdoCash);
        rdoCash.setText("Cash");

        rdgCaraBayar.add(rdoBCA);
        rdoBCA.setText("BCA Card");

        rdgCaraBayar.add(rdoMandiri);
        rdoMandiri.setText("Mandiri Card");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoMandiri)
                    .addComponent(rdoBCA)
                    .addComponent(rdoCash))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBCA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoMandiri)
                .addGap(34, 34, 34))
        );

        lblCaraBayar.setText("Cara Bayar");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu)
                            .addComponent(chkSate)
                            .addComponent(chkEsJeruk)
                            .addComponent(chkSoto)
                            .addComponent(chkEsTeh)
                            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCaraBayar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHitung)
                    .addComponent(jLabel2)
                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKosong))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSate)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsJeruk)
                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsTeh)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(btnHitung)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKosong)
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCaraBayar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSotoActionPerformed

    private void txtSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSateActionPerformed

    private void txtEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEsTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsTehActionPerformed

    private void txtEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEsJerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsJerukActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        // TODO add your handling code here:
    if (chkSoto.isSelected()) {
    txtSoto.setEditable(true);
    txtSoto.setText("1");
    } else {
    txtSoto.setEditable(false);
    txtSoto.setText("0");
    }
    }//GEN-LAST:event_chkSotoActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        // TODO add your handling code here:
        if (chkSate.isSelected()) {
        txtSate.setEditable(true);
        txtSate.setText("1");
        } else {
        txtSate.setEditable(false);
        txtSate.setText("0");
        }
    }//GEN-LAST:event_chkSateActionPerformed

    private void chkEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsJerukActionPerformed
        // TODO add your handling code here:
        if (chkEsJeruk.isSelected()) {
        txtEsJeruk.setEditable(true);
        txtEsJeruk.setText("1");
        } else {
        txtEsJeruk.setEditable(false);
        txtEsJeruk.setText("0");
        }
    }//GEN-LAST:event_chkEsJerukActionPerformed

    private void chkEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsTehActionPerformed
        // TODO add your handling code here:
        if (chkEsTeh.isSelected()) {
        txtEsTeh.setEditable(true);
        txtEsTeh.setText("1");
        } else {
        txtEsTeh.setEditable(false);
        txtEsTeh.setText("0");
        }
    }//GEN-LAST:event_chkEsTehActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
// TODO add your handling code here:
boolean lDataOke = true;
// cek Ada atau tidak :
// menu dipesan tetapi tidak menuliskan Quantity
// jika ada, maka variabel lDataOke menjadi false
if (chkSoto.isSelected() && txtSoto.getText() == " ")
lDataOke = false;
if (chkSate.isSelected() && txtSate.getText() == " ")
lDataOke = false;
if (chkEsJeruk.isSelected() && txtEsJeruk.getText() == " ")
lDataOke = false;
if (chkEsTeh.isSelected() && txtEsTeh.getText() == " ")
lDataOke = false;
// jika variabel lDataOke == false, berarti masih ada kesalahan
// sehingga perlu dimunculkan pesan kesalahan
if (!lDataOke) {
JOptionPane.showMessageDialog(this,
"Data Dilengkapi dahulu");
} else {
// untuk memudahkan, buat variabel baru untuk menampung data
int nSoto = Integer.parseInt(txtSoto.getText());
int nSate = Integer.parseInt(txtSate.getText());
int nEsJeruk = Integer.parseInt(txtEsJeruk.getText());
int nEsTeh = Integer.parseInt(txtEsTeh.getText());
// hitung total
int nTotal = (5000 * nSoto)+
(10000 * nSate)+(2000 * nEsJeruk)+(1500 * nEsTeh);
lblTotal.setText("Rp. "+nTotal);
// bagian ini untuk menampilkan cara Bayar
if (rdoCash.isSelected())
lblCaraBayar.setText(rdoCash.getActionCommand());
if (rdoBCA.isSelected())
lblCaraBayar.setText(rdoBCA.getActionCommand());
if (rdoMandiri.isSelected())
lblCaraBayar.setText(rdoMandiri.getActionCommand());
}

    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
chkSoto.setSelected(false);
chkSate.setSelected(false);
chkEsJeruk.setSelected(false);
chkEsTeh.setSelected(false);
txtSoto.setText("0");
txtSate.setText("0");
txtEsJeruk.setText("0");
txtEsTeh.setText("0");
txtSoto.setEditable(false);
txtSate.setEditable(false);
txtEsJeruk.setEditable(false);
txtEsTeh.setEditable(false);
rdoCash.setSelected(true);
lblTotal.setText("Rp. 0");
lblCaraBayar.setText("Cara Bayar");
    }//GEN-LAST:event_btnKosongActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fwarung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fwarung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fwarung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fwarung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fwarung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKosong;
    private javax.swing.JCheckBox chkEsJeruk;
    private javax.swing.JCheckBox chkEsTeh;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel lblCaraBayar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel menu;
    private javax.swing.ButtonGroup rdgCaraBayar;
    private javax.swing.JRadioButton rdoBCA;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoMandiri;
    private javax.swing.JTextField txtEsJeruk;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    // End of variables declaration//GEN-END:variables

    }
